import { Task } from '@/types/task-management'

export const mockTasks: Task[] = [
  {
    id: 'TSK-1001',
    title: 'Finalize Q3 Marketing Budget',
    description: 'Review and approve the final marketing budget for Q3, including all digital and print campaigns.',
    project: 'Q3 Financial Planning',
    department: 'Marketing',
    assignee: 'Sarah Chen',
    owner: 'Michael Scott',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-06-30',
    completionPercentage: 65,
    comments: [],
    attachments: [],
  },
  {
    id: 'TSK-1002',
    title: 'Update Employee Handbook',
    description: 'Incorporate the new remote work policies into the central employee handbook.',
    project: 'HR Policy Update',
    department: 'Human Resources',
    assignee: 'John Doe',
    owner: 'Sarah Chen',
    status: 'review',
    priority: 'medium',
    dueDate: '2026-07-05',
    completionPercentage: 90,
    comments: [],
    attachments: [],
  },
  {
    id: 'TSK-1003',
    title: 'Security Audit Preparation',
    description: 'Gather all necessary documentation for the upcoming SOC2 security audit.',
    project: 'SOC2 Compliance',
    department: 'Engineering',
    assignee: 'Alex Miller',
    owner: 'David Kim',
    status: 'draft',
    priority: 'urgent',
    dueDate: '2026-07-15',
    completionPercentage: 10,
    comments: [],
    attachments: [],
  },
  {
    id: 'TSK-1004',
    title: 'Design New Task Module',
    description: 'Create the initial UX mockups and component architecture for the Task Workspace.',
    project: 'G2G Platform v2',
    department: 'Design',
    assignee: 'Emily Davis',
    owner: 'Sarah Chen',
    status: 'completed',
    priority: 'high',
    dueDate: '2026-06-20',
    completionPercentage: 100,
    comments: [],
    attachments: [],
  },
  {
    id: 'TSK-1005',
    title: 'Fix Hydration Error in Dashboard',
    description: 'Investigate and resolve the React hydration mismatch caused by browser extensions.',
    project: 'G2G Platform v2',
    department: 'Engineering',
    assignee: 'John Doe',
    owner: 'David Kim',
    status: 'blocked',
    priority: 'medium',
    dueDate: '2026-06-26',
    completionPercentage: 40,
    comments: [],
    attachments: [],
  }
]
