"use client";
/* eslint-disable react-hooks/static-components, react-hooks/refs */
import { useEffect, useRef, useState } from "react";
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, Bold, ChevronDown, Code2, Eraser, Highlighter, Image as ImageIcon, Italic, Link, List, ListOrdered, Redo2, Table2, Underline, Undo2 } from "lucide-react";
import { Button } from "@/components/ui/button";
// LMS_K12's `TemplateHtmlEditor`, verbatim, with `TemplateTag` inlined from its api module.
type TemplateTag = { key: string; label: string };
type Props={value:string;onChange:(html:string)=>void;tags:TemplateTag[];disabled?:boolean};
const FONT_FAMILIES = ["Arial", "Arial Black", "Arial Narrow", "Book Antiqua", "Calibri", "Cambria", "Comic Sans MS", "Courier New", "Georgia", "Helvetica", "Impact", "Josefin Sans", "Lucida Console", "Lucida Sans Unicode", "Palatino Linotype", "Segoe UI", "Tahoma", "Times New Roman", "Trebuchet MS", "Verdana"] as const;
const COLOR_PALETTE = ["#000000","#374151","#9ca3af","#ef4444","#f97316","#eab308","#84cc16","#22c55e","#10b981","#06b6d4","#3b82f6","#8b5cf6","#ec4899","#ffffff"];
export function TemplateHtmlEditor({value,onChange,tags,disabled}:Props){
 const ref=useRef<HTMLDivElement>(null); const savedRangeRef=useRef<Range|null>(null); const [preview,setPreview]=useState(false); const [codeView,setCodeView]=useState(false); const [tablePicker,setTablePicker]=useState(false); const [tableSize,setTableSize]=useState({ rows: 5, columns: 5 }); const [tableGrid,setTableGrid]=useState({ rows: 5, columns: 5 }); const [fontColor,setFontColor]=useState("#000000"); const [highlightColor,setHighlightColor]=useState("#ffff00"); const [showFontColorPalette,setShowFontColorPalette]=useState(false); const [showHighlightColorPalette,setShowHighlightColorPalette]=useState(false); const [editorHeight,setEditorHeight]=useState(200); const heightStartRef=useRef<{y:number;height:number}|null>(null);
 useEffect(()=>{if(ref.current&&ref.current.innerHTML!==value)ref.current.innerHTML=value},[value]);
 const sync=()=>onChange(ref.current?.innerHTML??"");
 const saveSelection=()=>{const sel=window.getSelection();if(sel&&sel.rangeCount>0)savedRangeRef.current=sel.getRangeAt(0)};
 const cmd=(name:string,val?:string)=>{ref.current?.focus();if(savedRangeRef.current){const sel=window.getSelection();if(sel){sel.removeAllRanges();sel.addRange(savedRangeRef.current)}};if(name==="formatBlock")document.execCommand("defaultParagraphSeparator",false,"p");document.execCommand(name,false,name==="formatBlock"&&val?`<${val}>`:val);sync()};
 const Tool=({title,children,onClick}:{title:string;children:React.ReactNode;onClick:()=>void})=><Button type="button" variant="ghost" size="sm" className="h-8 min-w-8 px-2" title={title} onMouseDown={e=>e.preventDefault()} onClick={onClick} disabled={disabled}>{children}</Button>;
 const link=()=>{const url=window.prompt("Link URL");if(url)cmd("createLink",url)}; const image=()=>{const url=window.prompt("Image URL");if(url)cmd("insertHTML",`<img src="${url.replace(/"/g,"&quot;")}" alt="" style="max-width:100%;height:auto;" />`)};
  const insertTable=(rows:number,columns:number)=>{const cells=Array.from({length:columns},()=>"<td>&nbsp;</td>").join("");cmd("insertHTML",`<table class="template-editor-table" style="width:100%;border-collapse:collapse"><tbody>${Array.from({length:rows},()=>`<tr>${cells}</tr>`).join("")}</tbody></table><p></p>`);setTablePicker(false)};
  const RESIZE_THRESHOLD=8;
  const findTableEdge=(e:MouseEvent)=>{const target=e.target;if(!(target instanceof HTMLElement))return null;const cell=target.closest("td,th");if(!cell)return null;const table=cell.closest("table") as HTMLTableElement;if(!table)return null;const cellRect=cell.getBoundingClientRect();const tableRect=table.getBoundingClientRect();if(Math.abs(e.clientX-cellRect.right)<RESIZE_THRESHOLD){const row=cell.closest("tr")!;const cells=Array.from(row.children);const colIndex=cells.indexOf(cell);if(colIndex<cells.length-1)return{type:"column" as const,table,cell:cell as HTMLElement,colIndex}}if(Math.abs(e.clientY-cellRect.bottom)<RESIZE_THRESHOLD){const row=cell.closest("tr")!;const rows=Array.from(table.rows);const rowIndex=rows.indexOf(row);if(rowIndex<rows.length-1)return{type:"row" as const,table,cell:cell as HTMLElement,rowIndex}}if(Math.abs(e.clientX-tableRect.right)<RESIZE_THRESHOLD&&Math.abs(e.clientY-tableRect.bottom)<RESIZE_THRESHOLD)return{type:"table" as const,table};return null};
  const startTableResize=(e:MouseEvent,edge:{type:"column"|"row"|"table";table:HTMLTableElement;cell?:HTMLElement;colIndex?:number;rowIndex?:number})=>{e.preventDefault();const table=edge.table;const startX=e.clientX;const startY=e.clientY;if(edge.type==="column"&&edge.cell&&edge.colIndex!==undefined){const startWidth=edge.cell.offsetWidth;const colIndex=edge.colIndex;const onMove=(ev:MouseEvent)=>{const w=Math.max(20,startWidth+(ev.clientX-startX));table.querySelectorAll("tr").forEach(row=>{const cells=Array.from(row.querySelectorAll("td,th"));if(cells[colIndex])(cells[colIndex] as HTMLElement).style.width=`${w}px`})};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}else if(edge.type==="row"&&edge.cell&&edge.rowIndex!==undefined){const row=edge.cell.closest("tr")!;const startHeight=row.offsetHeight;const rowIndex=edge.rowIndex;const onMove=(ev:MouseEvent)=>{const h=Math.max(20,startHeight+(ev.clientY-startY));const rows=table.querySelectorAll("tr");if(rows[rowIndex])(rows[rowIndex] as HTMLElement).style.height=`${h}px`};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}else if(edge.type==="table"){const startWidth=table.offsetWidth;const startHeight=table.offsetHeight;const onMove=(ev:MouseEvent)=>{table.style.width=`${Math.max(100,startWidth+(ev.clientX-startX))}px`;table.style.height=`${Math.max(50,startHeight+(ev.clientY-startY))}px`};const onUp=()=>{sync();document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)}};
  const handleEditorMouseMove=(e:React.MouseEvent<HTMLDivElement>)=>{if(disabled)return;const edge=findTableEdge(e.nativeEvent);if(ref.current)ref.current.style.cursor=edge?edge.type==="column"?"col-resize":edge.type==="row"?"row-resize":"nwse-resize":""};
  const handleEditorMouseDown=(e:React.MouseEvent<HTMLDivElement>)=>{if(disabled)return;const edge=findTableEdge(e.nativeEvent);if(!edge)return;startTableResize(e.nativeEvent,edge)};
  const startHeightResize=(e:React.MouseEvent<HTMLDivElement>)=>{e.preventDefault();heightStartRef.current={y:e.clientY,height:editorHeight};const onMove=(ev:MouseEvent)=>{if(heightStartRef.current)setEditorHeight(Math.max(150,heightStartRef.current.height+(ev.clientY-heightStartRef.current.y)))};const onUp=()=>{heightStartRef.current=null;document.removeEventListener("mousemove",onMove);document.removeEventListener("mouseup",onUp)};document.addEventListener("mousemove",onMove);document.addEventListener("mouseup",onUp)};
 return <div className="mt-1 overflow-hidden rounded-none border border-slate-300 bg-white focus-within:border-slate-500">
  <div className="flex flex-wrap items-center gap-1 border-b border-slate-300 bg-white p-2">
   <select aria-label="Block format" className="h-8 rounded border bg-white px-2 text-xs" defaultValue="p" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("formatBlock",e.target.value)}><option value="p">Paragraph</option><option value="h1">Heading 1</option><option value="h2">Heading 2</option><option value="h3">Heading 3</option><option value="h4">Heading 4</option><option value="h5">Heading 5</option><option value="h6">Heading 6</option><option value="blockquote">Quote</option></select>
   <select aria-label="Font family" className="h-8 rounded border bg-white px-2 text-xs" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("fontName",e.target.value)}><option value="">Font</option>{FONT_FAMILIES.map(font=><option key={font} value={font}>{font}</option>)}</select><select aria-label="Font size" className="h-8 rounded border bg-white px-2 text-xs" onMouseDown={saveSelection} disabled={disabled} onChange={e=>cmd("fontSize",e.target.value)}><option value="">Size</option><option value="2">Small</option><option value="3">Normal</option><option value="4">Large</option><option value="5">X-Large</option></select>
   <Tool title="Bold" onClick={()=>cmd("bold")}><Bold className="size-4"/></Tool><Tool title="Italic" onClick={()=>cmd("italic")}><Italic className="size-4"/></Tool><Tool title="Underline" onClick={()=>cmd("underline")}><Underline className="size-4"/></Tool>
   <div className="relative"><Button type="button" variant="ghost" size="sm" className="h-8 min-w-10 px-2" title="Text Color" disabled={disabled} onMouseDown={e=>{e.preventDefault();saveSelection()}} onClick={()=>setShowFontColorPalette(!showFontColorPalette)}><span className="relative flex items-center"><span className="text-base font-bold" style={{color:fontColor}}>A</span><span className="absolute bottom-[-2px] left-0 right-0 h-[3px]" style={{backgroundColor:fontColor}}></span></span><ChevronDown className="ml-1 size-3 opacity-40"/></Button>{showFontColorPalette&&<div className="absolute top-full left-0 z-50 w-48 rounded-md border border-slate-200 bg-white p-2 shadow-lg"><div className="mb-2 text-xs font-medium text-slate-600">Text Color</div><div className="grid grid-cols-7 gap-1.5">{COLOR_PALETTE.map(c=><button key={c} type="button" aria-label={c} title={c} className="size-7 cursor-pointer rounded border border-slate-300 hover:scale-110" style={{backgroundColor:c}} onClick={()=>{setFontColor(c);cmd('foreColor',c);setShowFontColorPalette(false)}}/>)}</div><input type="color" value={fontColor} onChange={e=>{setFontColor(e.target.value);cmd('foreColor',e.target.value);setShowFontColorPalette(false)}} className="mt-2 h-7 w-full cursor-pointer rounded border border-slate-300"/></div>}</div><div className="relative"><Button type="button" variant="ghost" size="sm" className="h-8 min-w-10 px-2" title="Highlight Color" disabled={disabled} onMouseDown={e=>{e.preventDefault();saveSelection()}} onClick={()=>setShowHighlightColorPalette(!showHighlightColorPalette)}><span className="relative flex items-center"><Highlighter className="size-4" style={{color:highlightColor}}/><span className="absolute bottom-[-2px] left-0 right-0 h-[3px]" style={{backgroundColor:highlightColor}}></span></span><ChevronDown className="ml-1 size-3 opacity-40"/></Button>{showHighlightColorPalette&&<div className="absolute top-full left-0 z-50 w-48 rounded-md border border-slate-200 bg-white p-2 shadow-lg"><div className="mb-2 text-xs font-medium text-slate-600">Highlight Color</div><div className="grid grid-cols-7 gap-1.5">{COLOR_PALETTE.map(c=><button key={c} type="button" aria-label={c} title={c} className="size-7 cursor-pointer rounded border border-slate-300 hover:scale-110" style={{backgroundColor:c}} onClick={()=>{setHighlightColor(c);cmd('hiliteColor',c);setShowHighlightColorPalette(false)}}/>)}</div><input type="color" value={highlightColor} onChange={e=>{setHighlightColor(e.target.value);cmd('hiliteColor',e.target.value);setShowHighlightColorPalette(false)}} className="mt-2 h-7 w-full cursor-pointer rounded border border-slate-300"/></div>}</div>
   <Tool title="Align left" onClick={()=>cmd("justifyLeft")}><AlignLeft className="size-4"/></Tool><Tool title="Align center" onClick={()=>cmd("justifyCenter")}><AlignCenter className="size-4"/></Tool><Tool title="Align right" onClick={()=>cmd("justifyRight")}><AlignRight className="size-4"/></Tool><Tool title="Justify" onClick={()=>cmd("justifyFull")}><AlignJustify className="size-4"/></Tool><Tool title="Bulleted list" onClick={()=>cmd("insertUnorderedList")}><List className="size-4"/></Tool><Tool title="Numbered list" onClick={()=>cmd("insertOrderedList")}><ListOrdered className="size-4"/></Tool><Tool title="Add link" onClick={link}><Link className="size-4"/></Tool><Tool title="Add image" onClick={image}><ImageIcon className="size-4"/></Tool><div className="relative"><Button type="button" variant="ghost" size="sm" className="h-8 min-w-8 px-2" title="Insert table" disabled={disabled} onMouseDown={event=>event.preventDefault()} onClick={()=>{setTableSize({rows:5,columns:5});setTableGrid({rows:5,columns:5});setTablePicker(open=>!open)}}><Table2 className="size-4"/></Button>{tablePicker&&<div className="absolute left-0 top-9 z-30 rounded-md border border-slate-200 bg-white p-2 shadow-lg" style={{width:`${tableGrid.columns*18+16}px`}}><div className="grid gap-0.5" style={{gridTemplateColumns:`repeat(${tableGrid.columns}, minmax(0, 1fr))`}}>{Array.from({length:tableGrid.rows*tableGrid.columns},(_,index)=>{const row=Math.floor(index/tableGrid.columns)+1;const column=index%tableGrid.columns+1;const selected=row<=tableSize.rows&&column<=tableSize.columns;return <button key={index} type="button" aria-label={`Insert ${row} by ${column} table`} className={`size-4 border transition-colors ${selected ? "border-blue-200 bg-blue-100" : "border-slate-200 bg-slate-50"}`} onMouseEnter={()=>{setTableSize({rows:row,columns:column});setTableGrid(current=>({rows:row===current.rows?Math.min(10,current.rows+1):current.rows,columns:column===current.columns?Math.min(10,current.columns+1):current.columns}))}} onMouseDown={event=>event.preventDefault()} onClick={()=>insertTable(row,column)}/>})}</div><div className="pt-2 text-center text-xs text-slate-600">{tableSize.rows} x {tableSize.columns}</div></div>}</div><Tool title="Horizontal line" onClick={()=>cmd("insertHorizontalRule")}>-</Tool><Tool title={codeView ? "Visual editor" : "Code view"} onClick={()=>{sync();setCodeView(current=>!current)}}><Code2 className="size-4"/></Tool><Tool title="Clear formatting" onClick={()=>cmd("removeFormat")}><Eraser className="size-4"/></Tool><Tool title="Undo" onClick={()=>cmd("undo")}><Undo2 className="size-4"/></Tool><Tool title="Redo" onClick={()=>cmd("redo")}><Redo2 className="size-4"/></Tool>
   {/* Hidden when there are no tags to insert: a generated report is already-rendered
       data with no <<tokens>> in it, and an empty picker is a control that does nothing. */}
   {tags.length>0&&<select aria-label="Insert template variable" className="h-8 max-w-56 rounded border bg-white px-2 text-xs" onMouseDown={saveSelection} defaultValue="" disabled={disabled} onChange={e=>{if(e.target.value){cmd("insertHTML",`&lt;&lt; ${e.target.value} &gt;&gt;`);e.target.value=""}}}><option value="">Insert template variable...</option>{tags.map(t=><option key={t.key} value={t.key}>{t.key} - {t.label}</option>)}</select>}<Button type="button" size="sm" variant="outline" className="h-8" disabled={disabled} onClick={()=>setPreview(true)}>Preview</Button>
  </div>{codeView ? <textarea aria-label="HTML content code view" value={value} disabled={disabled} onChange={event=>onChange(event.target.value)} style={{height:editorHeight}} className="w-full resize-y border-0 bg-slate-950 p-3 font-mono text-sm leading-6 text-slate-100 outline-none" /> : <div ref={ref} contentEditable={!disabled} suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="HTML content visual editor" onInput={sync} onBlur={sync} onMouseMove={handleEditorMouseMove} onMouseDown={handleEditorMouseDown} style={{height:editorHeight}} className="overflow-auto p-3 text-sm leading-6 outline-none [&_table]:border-collapse [&_table]:!border-0 [&_td]:!border-0 [&_td]:p-2 [&_th]:!border-0 [&_th]:p-2 [&_h1]:my-3 [&_h1]:text-3xl [&_h1]:font-bold [&_h2]:my-2 [&_h2]:text-2xl [&_h2]:font-bold [&_h3]:my-2 [&_h3]:text-xl [&_h3]:font-semibold [&_h4]:my-2 [&_h4]:text-lg [&_h4]:font-semibold [&_h5]:my-2 [&_h5]:text-base [&_h5]:font-semibold [&_h6]:my-2 [&_h6]:text-sm [&_h6]:font-semibold [&_blockquote]:my-3 [&_blockquote]:border-l-4 [&_blockquote]:border-slate-300 [&_blockquote]:pl-4 [&_.template-editor-table]:!border [&_.template-editor-table]:!border-slate-300 [&_.template-editor-table_td]:!border [&_.template-editor-table_td]:!border-slate-300 [&_.template-editor-table_td]:!p-2"/>}
  {preview&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" role="dialog" aria-modal="true"><div className="flex h-[min(85vh,900px)] w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">Template preview</h2><Button variant="ghost" size="sm" onClick={()=>setPreview(false)}>Close</Button></div><iframe title="Template preview" srcDoc={ref.current?.innerHTML??value} className="min-h-0 flex-1 bg-white"/></div></div>}
   {!disabled&&<div className="h-1 cursor-ns-resize bg-slate-300 hover:bg-slate-400" onMouseDown={startHeightResize} title="Drag to resize editor height"/>}
 </div>
}