'use client'

import { memo } from 'react'
import { InfiniteSpiral, type InfiniteSpiralItem } from '@/components/auth/login/infinite-spiral'

/*
 * ═══════════════════════════════════════════════════════════════════════════
 * NINE INDUSTRIES, NOT A MOOD BOARD
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * What this replaces: a 3-image crossfading collage of AI-invented UI stat
 * cards with text baked into the PNG pixels. Rejected outright. This is real
 * photography (no fake dashboards, no baked-in text — the label below is
 * real DOM text), one card per industry G2G serves, weighted toward the
 * product's actual priority: employee capability/skills-gap closing is the
 * #1 story, talent management #2, LMS #3. Task management and other modules
 * carry deliberately little weight here — of these 9, 5 lean on capability,
 * 2 on talent, 2 on LMS, 0 dedicated to task management.
 *
 * (Started at 15 industries; cut to this 9 when the user supplied exactly
 * these 9 generated photos and asked for a sparser, larger-card spiral —
 * Logistics/Hospitality/Construction/Insurance/Automotive/Telecom dropped,
 * not because their capability story was weaker, purely to match what was
 * actually generated.)
 *
 * The pairings are grounded in what G2G actually does, not invented copy —
 * see the plan file for the full trace, but briefly: `services/competency/
 * gap.ts` computes a real, literal skills gap; a course-builder toggle
 * called "Update capability records when a learner passes" means finishing
 * a mapped LMS course automatically closes the gap it was assigned for; the
 * AI resume screener outputs `skill_gaps` on candidates pre-hire, so talent
 * and capability already share one vocabulary in this product. The label on
 * each card is just the industry name — "what it solves" lives in the
 * curation (which industry got a capability-weighted slot vs a talent- or
 * LMS-weighted one), not in a written-out sentence that wouldn't fit a card
 * anyway.
 *
 * ── WHERE THE PHOTOS COME FROM ───────────────────────────────────────────
 *
 * Generated by the user via an AI image tool, from prompts written and
 * reviewed in the planning pass for this change (see the plan file) — full-
 * color source photography, no baked-in text, no people/hands/faces, square
 * composition. Delivered as 1254×1254 PNGs (1.7-2.5MB each); resized to
 * 600×600 JPEG (45-84KB each) before landing here — `next.config.mjs` has
 * `images: { unoptimized: true }`, so there is no server-side resize
 * pipeline and whatever ships is exactly what downloads; unprocessed
 * originals at card-thumbnail scale would have shipped 20-50x oversized.
 * Shown in full color — an initial pass desaturated via the component's own
 * `grayscale` prop (non-destructive, no source-image changes needed), but
 * that's been removed; full color reads better against the navy panel with
 * this particular set.
 *
 * Filenames are the lowercase, hyphenated industry name — `real-estate.jpg`
 * for "Real Estate", everything else is a single word.
 */

const SPIRAL_ITEMS: InfiniteSpiralItem[] = [
  { src: '/auth/spiral/healthcare.jpg', alt: '', label: 'Healthcare' },
  { src: '/auth/spiral/technology.jpg', alt: '', label: 'Technology' },
  { src: '/auth/spiral/real-estate.jpg', alt: '', label: 'Real Estate' },
  { src: '/auth/spiral/education.jpg', alt: '', label: 'Education' },
  { src: '/auth/spiral/electronics.jpg', alt: '', label: 'Electronics' },
  { src: '/auth/spiral/manufacturing.jpg', alt: '', label: 'Manufacturing' },
  { src: '/auth/spiral/retail.jpg', alt: '', label: 'Retail' },
  { src: '/auth/spiral/finance.jpg', alt: '', label: 'Finance' },
  { src: '/auth/spiral/government.jpg', alt: '', label: 'Government' },
]

/*
 * `memo()` + `SPIRAL_ITEMS` at module scope, together, are load-bearing —
 * not just tidiness. `LoginPage` re-renders on every keystroke in the
 * email/password fields (this panel is a sibling of <main> in the same
 * returned tree); the animation effect inside InfiniteSpiral depends on the
 * memoized items array, so if that array were recreated per render, every
 * keystroke would bust the memo, bust the effect's deps, and tear down and
 * rebuild the entire ResizeObserver/IntersectionObserver/requestAnimationFrame
 * loop. `memo()` here means SpiralGallery never re-renders after mount in
 * the first place — there's nothing in its own props that would need it to.
 * (Verified empirically, not just by reasoning about it: sampled a card's
 * transform at a steady cadence across a typing event and checked for a
 * discontinuity — none found, see the plan file's verification notes.)
 */
export const SpiralGallery = memo(function SpiralGallery({ className }: { className?: string }) {
  return (
    <InfiniteSpiral
      items={SPIRAL_ITEMS}
      className={className}
      animationMode="all"
      speed={0.45}
      direction="up"
      radius={200}
      cardWidth={150}
      cardHeight={150}
      /*
       * 130, not 75 — the previous value let the front-most card visually
       * cover its nearest neighbors. `centerScale` (below) compounds with
       * the perspective depth boost on the card closest to the viewer, so
       * the front card actually peaks around 1.4x — a 150px card rendering
       * at ~210px — and 75px of vertical separation wasn't enough room for
       * that size; diagnosed by inspecting live opacity/position on every
       * card mid-rotation, not just from the numbers (one card was
       * genuinely at opacity 0, another had its top half hidden under the
       * oversized card in front of it, at that exact frame). Verified
       * empirically at 130 across a full rotation, not just reasoned about
       * — see the plan file's verification notes.
       */
      verticalSpacing={130}
      perspective={1100}
      /*
       * 5, not 7 — dropped further when the item pool dropped from 15 to 9.
       * cardsPerTurn is the angular pitch of one revolution, independent of
       * total item count; keeping it at 7 against only 9 items would have
       * given barely more than one full turn (9/7 ≈ 1.3), flattening the
       * helix back toward the "merry-go-round" look this was tuned away
       * from earlier. At 5, nine items wrap into 1.8 turns — a real
       * multi-coil stack, and (combined with edgeFade below) fewer cards
       * sit in the fully-legible foreground band at once, matching the
       * "5-6 visible, not 10" ask directly.
       */
      cardsPerTurn={5}
      cardTilt={0}
      cardRadius={12}
      centerScale={1.25}
      /*
       * 0.4, not 0.35 — a larger fraction of the outer travel range fades
       * out, so with bigger cards and a sparser pool, fewer are at full
       * opacity in the foreground simultaneously rather than crowding the
       * panel.
       */
      edgeFade={0.4}
      edgeBlur={6}
      pauseOnHover
      imageFit="cover"
    />
  )
})
